# Use the PyTorch image as the base
FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PIP_PREFER_BINARY=1
ENV ROOT=/stable-diffusion-webui
ENV NVIDIA_VISIBLE_DEVICES=all

# Install system dependencies
RUN apt-get update && apt-get install -y \
    fonts-dejavu-core \
    rsync \
    git \
    jq \
    moreutils \
    aria2 \
    ffmpeg \
    libglfw3-dev \
    libgles2-mesa-dev \
    pkg-config \
    libcairo2 \
    libcairo2-dev \
    build-essential \
    libgoogle-perftools-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set up stable-diffusion-webui
WORKDIR /
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git ${ROOT} && \
    cd ${ROOT} && \
    git reset --hard v1.9.4 && \
    pip install -r requirements_versions.txt


# Copy the v1-5-pruned-emaonly.ckpt model
COPY v1-5-pruned-emaonly.ckpt ${ROOT}/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt


# Install additional dependencies
RUN pip install --no-cache-dir \
    pyngrok \
    xformers==0.0.26.post1 \
    git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 \
    git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 \
    git+https://github.com/mlfoundations/open_clip.git@v2.20.0 \
    typing_extensions \
    altair==4.1.0

# Set up tcmalloc
ENV LD_PRELOAD=libtcmalloc.so

# Apply the gradio routes fix
RUN sed -i 's/in_app_dir = .*/in_app_dir = True/g' /opt/conda/lib/python3.10/site-packages/gradio/routes.py

# Set up git config
RUN git config --global --add safe.directory '*'

# Set working directory
WORKDIR ${ROOT}

# Expose port
EXPOSE 7860
